spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  jpa:
    show-sql: true
